### ISSUE TITLE
Add optional 'opts' argument to sort function

### ISSUE THREAD

**Issue by matteocng** [Kikobeats/sort-keys-recursive#2]
I am using this module via [bumped-finepack](https://github.com/bumped/bumped-finepack) ([bumped](https://github.com/bumped/bumped) -> [bumped-finepack](https://github.com/bumped/bumped-finepack) -> [finepack](https://github.com/Kikobeats/finepack) -> sort-keys-recursive) on this `package.json`:

```json
{
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "at-rule-no-unknown": [
        true,
        {
          "ignoreAtRules": [
            "each"
          ]
        }
      ]
    }
  }
}
```

This is the output:

```json
{
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "at-rule-no-unknown": [
        {
          "ignoreAtRules": [
            "each"
          ]
        },
        true
      ]
    }
  }
}
```

Unfortunately [sort()](https://github.com/Kikobeats/sort-keys-recursive/blob/master/index.js#L27) (correctly) sorts `at-rule-no-unknown` and breaks stylelint, leaving two choices: disabling linting or having to move the whole object outside `package.json`.

A simple, backwards compatible solution for these cases could be to change the [sort](https://github.com/Kikobeats/sort-keys-recursive/blob/master/index.js#L35) function to accept a new, third optional argument of type `object` and name `opts`:

`function sort (something, compareFn, opts) {`

The `opts` object could be structured like this:

```js
var options = {
  ignoreObjectAtKeys: [ // or skipObjectAtKeys.
      'rules'
  ],
  ignoreArrayAtKeys: [ // or skipArrayAtKeys. Not needed in this case, but nice to have too.
  ]
}
```
It would be easy to ignore the requested arrays/objects with a quick check in the [main loop](https://github.com/Kikobeats/sort-keys-recursive/blob/master/index.js#L17).

Then a small modification to [finepack](https://github.com/Kikobeats/finepack#api) to document the new key in `options`, which may be called `sortOptions`:

```js
var options = {
  filename: filename, // for customize the output messages, but is not necessary.
  validate: false, // For enable (or not) keys validation (false by default).
  color: false, // For enable (or not) colorize or not the output (false by default).
  sortOptions: { // Options to pass to the sort module that is used internally.
    ignoreObjectAtKeys, // don't sort the Object at the specified key, if any. 
    ignoreArrayAtKeys // don't sort the Array at the specified key, if any.
  }
}
```

[finepack](https://github.com/Kikobeats/finepack#api) would check if `sortOptions` was true and in case [pass it to this module](https://github.com/Kikobeats/finepack/blob/master/lib/Finepack.coffee#L50) as the third argument.

I could submit PRs to both modules with the small mods to code, readme and tests.

**Comment by Kikobeats** [comment]
I understand your problem, but looks a very specific case for be handle in this library?

why `true`? exists a way to prefix the value with a keyword?

**Comment by matteocng** [comment]
Hello @kikobeats, unfortunately the [stylelint <code>rules</code> object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#rules) only allows an array with two values when you need to pass configuration to a rule; the first must be a boolean | string (depends on the allowed values for the 'rule') and the second an object.

Even in those cases where the expected first value is a string such as "always", the default sort function would still move the object to the start of the array and break the rule: e.g <code>["always", {}].sort()</code>. The only exception could be modifying stylelint to allow <code>1</code> as an alias of boolean true (sort() would not switch the elements then), but It would almost certainly be rejected or seen as not necessary.

I agree that the use case is specific, but I think that the proposed configuration parameters can be considered generic and make the module more configurable.  😄

**Comment by Kikobeats** [comment]
Check it: https://github.com/Kikobeats/finepack/blob/master/lib/Finepack.coffee#L48

By default I'm using sort alphabetically using this library but later I sort a set of properties for esthetic. 

Have sense add this new feature and also update finepack for handle it correctly.

what do you think about PR? 😄

**Comment by matteocng** [comment]
👍 next PR is for finepack.

**Comment by Kikobeats** [comment]
@matteocng I'm going to release v2, thanks for that 😄
